"""empty message

Revision ID: 2bd07ec935e8
Revises: 32d12315ec03
Create Date: 2019-05-03 10:39:30.303744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd07ec935e8'
down_revision = '32d12315ec03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nc_users', sa.Column('last_time', sa.DateTime(), nullable=True))
    op.add_column('nc_users', sa.Column('name', sa.String(length=35), nullable=False))
    op.add_column('nc_users', sa.Column('picture', sa.String(length=55), nullable=True))
    op.add_column('nc_users', sa.Column('surname', sa.String(length=35), nullable=False))
    op.alter_column('nc_users', 'confirm_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('nc_users', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.create_unique_constraint(None, 'nc_users', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nc_users', type_='unique')
    op.alter_column('nc_users', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('nc_users', 'confirm_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.drop_column('nc_users', 'surname')
    op.drop_column('nc_users', 'picture')
    op.drop_column('nc_users', 'name')
    op.drop_column('nc_users', 'last_time')
    # ### end Alembic commands ###
